### ISSUE TITLE
Cannot overwrite the name of calculated quantities

### ISSUE THREAD

**Issue by joshcalcino** [danieljprice/splash#16]
At the moment it seems like splash will read `splash.columns` before it computes any additional calculated quantities, leading to the following warning

```
WARNING: array limits reached reading splash.columns, max =     14
 read splash.units

 Current list of calculated quantities:
 15) r = sqrt((x-x0)**2 + (y-y0)**2 + (z-z0)**2)        [OK]
```

An easy fix to this might be to just change the order of these so that splash.columns is read after the additional quantities are calculated, but I am not sure if this would interfere with anything else in splash.

**Comment by danieljprice** [comment]
I forgot why this was a problem. What were you trying to do here?
