### ISSUE TITLE
splash calc tracks doesn't produce the .out file

### ISSUE THREAD

**Issue by Francyrad** [danieljprice/splash#45]
Dear professor Daniel Price

The bug of splash is about the command "splash calc tracks" command. It doesn't work on StarSmasher but neither in Swiftsim...

The others splash calc commands works very well and they produce the file that they promise to produce. However the splash calc tracks doesn't work, here is what happens (with Starsmasher, i also tried it in swiftsim and it doesn't work also there)

First i use /xw and i press "t" to select the particles, then

q

l

I can see the particle that is been saved, i set then the particle limits

set
set
set
set

0

and then i press S to produce tha splash.limits file

Then i press q and i write:

jsplash (i did this alias for the StarSmasher command) calc tracks out*.sph

And it starts to write so:

read splash.defaults
         501  filenames read from command line
----------------------- out0000.sph -----------------------
 time             :    1.1040916432267327E-002
 N_total          :       139896
 N data columns   :           13
 >> last step ntot =      139896
 read splash.units
 read splash.limits

-----> CALCULATING tracks vs time for all dump files

-----> CALCULATING TRACKS, TIME= 2.04E-04 FILE #    1

And so on for the others 500 snaps. At the end it writes:

----------------------- out0499.sph -----------------------
 time             :    49.906836273424069    
 N_total          :       139896
 N data columns   :           13
 >> last step ntot =      139896

-----> CALCULATING TRACKS, TIME= 9.21E-01 FILE #  500

----------------------- out0500.sph -----------------------
 time             :    50.002533158971630    
 N_total          :       139896
 N data columns   :           13
 >> last step ntot =      139896

-----> CALCULATING TRACKS, TIME= 9.22E-01 FILE #  501

-----> FINISHED CALCULATING TRACKS (USED 501 DUMP FILES)

But no file tracks-123.out is been created! I hoped that this command could sign the x y z cordiantes of the particles vs time and produce a picture that is pretty similar to the figure 10 of this paper:

https://iopscience.iop.org/article/10.1088/0004-637X/786/1/39/pdf

I sent an email some weeks ago, but without answer. Here there are some StarSmasher snapshots.

Best regards

Francesco

**Comment by Francyrad** [comment]
@danieljprice any news about this bug, the last version still doesn't produce the file "tracks-123.out" after have selected a particle with "t" in the interactive plot. It would be useful to make a plot and see all the path of a particle during the simulation. It doesn't work in any code...


Thank you for your hard work

Francesco

**Comment by danieljprice** [comment]
now fixed

**Comment by Francyrad** [comment]
It works! But there is some problem in the file:

The values inside the file are correct, but when reading with splash the titles are not correct:

Inside we have:
# [01         time]  [02 x [R_{sun}] ]  [03 y [R_{sun}] ]  [04 z [R_{sun}] ]  [05 v_x         ]  [06 v_y         ]  [07 v_z         ]  [08 particle mas]  [09 density[g/cm]  [10 specific int]  [11 mean_mu     ]  [12 h           ]  [13 du/dt       ]  [14 temperature ]


But when we read it with splash (or splash -ev) it says:
 1) time                   8) v_x                 
   2) x R_{sun}              9) v_y                 
   3) column   3            10) v_z                 
   4) y R_{sun}             11) particle mas        
   5) column   5            12) densityg/cm         
   6) z R_{sun}             13) specific int        
   7) column   7            14) mean_mu      


When i use just splash, the values are correct, even if column 3 in truth is y Rsun. However when i use the -ev, the values are not the promised one.

I attach you the file, we've no idea where the problem is.

(i obviously read the file in another folder without other splash.defaults or similar files)

Thank you for your work!

Francesco


[tracks.zip](https://github.com/danieljprice/splash/files/6377236/tracks.zip)
