### ISSUE TITLE
bug: impossible to color the particles on swiftsim

### ISSUE THREAD

**Issue by Francyrad** [danieljprice/splash#47]
Dear Professor Daniel Price

On Swiftsim simulations, it's impossible to color a set of particles and follow them, as you can see from these 2 snapshots, advancing in the simulation will result in a kind of color bug 

![Schermata da 2021-03-07 15-14-32](https://user-images.githubusercontent.com/51544149/110242805-f7ba5c00-7f57-11eb-8e5d-1a246a6859b7.png)
![Schermata da 2021-03-07 15-14-35](https://user-images.githubusercontent.com/51544149/110242809-f8eb8900-7f57-11eb-9acc-8551f5c3b988.png)
![Schermata da 2021-03-07 15-14-38](https://user-images.githubusercontent.com/51544149/110242812-fa1cb600-7f57-11eb-8ac8-e0df9d8f15de.png)
![Schermata da 2021-03-07 15-14-40](https://user-images.githubusercontent.com/51544149/110242816-fee16a00-7f57-11eb-93f6-5a52f742ae55.png)

I also attach some snapshots of the simulation in a zip file. I hope you can solve...

Best Regards and Thank you!

Francesco
[snapsfordaniel.zip](https://github.com/danieljprice/splash/files/6097265/snapsfordaniel.zip)

**Comment by danieljprice** [comment]
I think this is because the particle id is not read/used from SWIFT snapshots to re-order the particles. I can take a look but it may require a bit of work. Snapshots are helpful, thanks.

**Comment by Francyrad** [comment]
Thank you professor to work on that! Actually the 2 planets have a core and a mantle of 2 differents materials, and there are a lot avaiable on swiftsim..

I also opened an issue the 2 Feb about the command splash calc tracks, it do the calculations, but it doesn't produce the tracks-123.out file on Phantom, StarSmasher and SwiftSim... Let us know and thankyou!

Francesco

**Comment by Francyrad** [comment]
Dear professor Price. The bug is still present in the actual version of SPLASH. I forgot to attach you some hdf5 snaps. I hope that the bug can be fixed...
-Francesco

https://drive.google.com/drive/folders/1kc4OHVzMwGS9CN4wJXT4ZAmTmay7jLge?usp=sharing

**Comment by Francyrad** [comment]
It works perfectly now. Thank you!
