### ISSUE TITLE
(enhancement) Change marker type for given particle ID(s)

### ISSUE THREAD

**Issue by themikelau** [danieljprice/splash#56]
This would be a useful enhancement for tracking individual particles.

**Comment by Francyrad** [comment]
It's "impossible" to plot the 123track.out file worship splash -av x.out 

However it would be cool to have a file with multiples coordinates for each particle chosen

**Comment by danieljprice** [comment]
The way I usually do this is via the "plot error bars/circles of interaction" option in the o) menu. There you can enter specific particle IDs and identify/track them even in rendered plots from the overlaid smoothing circle. I guess you just want to change the marker for the particles whose smoothing circles are plotted?

**Comment by themikelau** [comment]
Thanks @danieljprice , I forgot about the ability to enter particle IDs in the o) menu. In that case, I don't personally need this enhancement.

**Comment by themikelau** [comment]
@Francyrad I will close this issue, but feel free to log a new issue with your suggestion.
