### ISSUE TITLE
build process broken after at commit b2c796329d4856a44ecee877e25411f1b7bacd3a 

### ISSUE THREAD

**Issue by richard-miller** [danieljprice/splash#9]
At commit b2c796329d4856a44ecee877e25411f1b7bacd3a  it seems the separation of giza from splash has caused the standard build / install process to break,  After this commit when I do:

  git clone https://github.com/danieljprice/splash.git
  cd splash; git clone https://github.com/danieljprice/giza.git
  make SYSTEM=gfortran withgiza

the build errors out with:

  gfortran -O3 -frecord-marker=4 -fopenmp -I../giza/include/ -c giza-fortran.F90 -o giza-fortran.o
  gfortran: error: giza-fortran.F90: No such file or directory
  gfortran: fatal error: no input files

If I reset to the previous commit:

  git reset --hard a5ddb7fe82f7122996beebda4a6f5799450e933d

all is good (assuming I leave the "withgiza" option out of the make).

**Comment by richard-miller** [comment]
PS The platform is a generic ubuntu box:

Linux happy 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by danieljprice** [comment]
Hi Richard,

 I just pushed a fix for this (c6b48928fcf3). Appeared to be only a problem under Linux. Typing "make withgiza" should now work as described in the docs.

Thanks for reporting

Daniel

**Comment by richard-miller** [comment]
Many thanks ...  Ill test on my next install ...



Richard Miller

Systems Administrator

Faculty of Science and Engineering  |   Room 355, Level 3, E6A Building
Macquarie University, NSW 2109, Australia

T: +61 2 9850 9587
M: + 61 418 217 245  |  mq.edu.au<http://mq.edu.au/>

[Macquarie University]<http://mq.edu.au/>

CRICOS Provider Number 00002J. Think before you print.
Please consider the environment before printing this email.

This message is intended for the addressee named and may
contain confidential information. If you are not the intended
recipient, please delete it and notify the sender. Views expressed
in this message are those of the individual sender, and are not
necessarily the views of Macquarie University.


________________________________
